version: '3.4'
services:
    # lb: 
    #   build: ./lb 
    #   ports:
    #     - "8000:80"
    app1: 
      container_name: server_one
      build: ./server1
      ports: 
        - "9001:3001"
      networks: 
        - mynet
        
    app2: 
      container_name: server_two
      build: ./server2
      ports:    
        - "9002:3002"
      networks:
        - mynet  
    redis:
      image: redis:alpine
networks:
    mynet:
      driver: bridge     
